### PR TITLE
Implement new archetype features:

### PR DESCRIPTION
**Pull request by kneelsdev**
- support affiliate and mint discounts
    - optional alternate owner address for withdrawals
    - super affiliate - receives half of platform fee
    - make affiliate fee modifiable.
    - add # of mints to Referral event

### CODE REVIEW

**Comment by kneelsdev** [comment]
Let me know what you think of the "mint tiers", I made it dynamic as it seemed more elegant and gives us a little more freedoms vs the 4 fixed rates.

**Comment by kneelsdev** [comment]
I made the affiliate fee modifiable with a lock.
Do we also want to have this for the mint and affiliate discount?

**Comment by h8ku** [comment]
> I made the affiliate fee modifiable with a lock. Do we also want to have this for the mint and affiliate discount?

Affiliate fee should only be able to be increased and never decreased.

**Comment by h8ku** [comment]
>  I made it dynamic as it seemed more elegant and gives us a little more freedom versus defining 4 fixed rates.

Making discount tiers flexible is A+.

**Comment by kneelsdev** [comment]
> > I made the affiliate fee modifiable with a lock. Do we also want to have this for the mint and affiliate discount?
> 
> Affiliate fee should only be able to be increased and never decreased.
> 
> This is important to protect affiliates who may otherwise get rugged by collection owners after they do the work of getting the affiliate links out there.
> 
> Affiliate fee locking I feel isn't as important but still okay to have. Affiliates may want to always increase the affiliate fee up to the max to increase the incentives for affiliates to get involved.

**Comment by kneelsdev** [comment]
> > I made the affiliate fee modifiable with a lock. Do we also want to have this for the mint and affiliate discount?
> 
> Affiliate fee should only be able to be increased and never decreased.
> 
> This is important to protect affiliates who may otherwise get rugged by collection owners after they do the work of getting the affiliate links out there.
> 
> Affiliate fee locking I feel isn't as important but still okay to have. Affiliates may want to always increase the affiliate fee up to the max to increase the incentives for affiliates to get involved.

One thing is If we prevent the owners from decreasing the affiliate fee then this would prevent them from being able to do timed boosts, like for example: "affiliates get 30% for the next week", Unless we add some more logic that can handle this case, and we remember the originally set rate.

**Comment by h8ku** [comment]
Temporary boosts up I think would be fine but if we enabled that we would want to surface the boost countdown on the affiliate page too. Supporting that does seem like a good idea because it can create urgency. As long as it's transparent and up only it's fine, like no temporary antiboosts down.

**Comment by kneelsdev** [comment]
Screenshot from 2022-05-25 20-22-33

**Comment by kneelsdev** [comment]
Screenshot from 2022-08-26 15-07-15

**Comment by kneelsdev** [comment]
Screenshot from 2022-08-26 16-46-23

**Review by coindegen — APPROVED** [review]

**Pull request merged**
